branches:
  only:
    - master

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages'

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:

  - cmd: dotnet pack src/Seq.App.Telegram/Seq.App.Telegram.csproj -p:PackageVersion="%GitVersion_NuGetVersion%" -c Release
  - cmd: dotnet nuget push **/*.nupkg -k "%AppVeyorNuGet_Key%" -s "%AppVeyorNuGet_Feed%"

