version: '{build}'

branches:
  only:
    - master

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages'

nuget:
  project_feed: true

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: Update-AppveyorBuild -Version $GitVersion_NuGetVersion

after_build:
  - ps: Push-Location src/Seq.App.Telegram
  - ps: dotnet publish -c Release -o ./obj/publish
  - ps: echo $GitVersion_NuGetVersion
  - ps: dotnet pack --no-build -c Release -o ./bin/nuget -p:PackageVersion="$GitVersion_NuGetVersion"
  - ps: Get-ChildItem -Recurse *.nupkg | % { Push-AppveyorArtifact $_ -FileName $_.Name }
 
